### PR TITLE
Added character driver project

### PR DESCRIPTION
**Pull request by gabrielshahrouzi**

### CODE REVIEW

**Comment by theyoyojo** [comment]
hey it looks like you included some binaries and swap files, can you remove them?

**Review by theyoyojo — CHANGES_REQUESTED** [review]
remove binaries and swap files please

**Comment by gShahr** [comment]
will do

**Review by theyoyojo — APPROVED** [review]
nice lgtm

**Review by theyoyojo — CHANGES_REQUESTED** [review]
I get an `impilcit declaration of copy_to_user` error, do you?

adding:
```c
#include <linux/uaccess.h>
```
fixes it for me

**Comment by gShahr** [comment]
Interesting. My machine did not give me a warning. Documentation says I had to include the header you have above in order to use copy_to_user. I'll add it rn

**Review by theyoyojo — APPROVED** [review]
lgtm

**Pull request merged**
